version: 2

models:
  - name: gold_user_analytics
    description: "Gold layer: Comprehensive user spending analytics and behavioral insights"
    columns:
      - name: user_id
        description: "Unique identifier for users"
        tests:
          - unique
          - not_null
      - name: total_transactions
        description: "Total number of transactions made by the user"
        tests:
          - not_null
      - name: completed_transactions
        description: "Number of successfully completed transactions"
        tests:
          - not_null
      - name: total_spent
        description: "Total amount spent by the user on completed transactions"
        tests:
          - not_null
      - name: customer_value_segment
        description: "Customer value segmentation based on spending"
        tests:
          - accepted_values:
              arguments:
                values: ['High Value', 'Medium Value', 'Low Value']

  - name: gold_merchant_analytics
    description: "Gold layer: Comprehensive merchant performance analytics and business insights"
    columns:
      - name: merchant_id
        description: "Unique identifier for merchants"
        tests:
          - unique
          - not_null
      - name: total_transactions
        description: "Total number of transactions at this merchant"
        tests:
          - not_null
      - name: success_rate_percent
        description: "Percentage of successful transactions"
        tests:
          - not_null
      - name: total_revenue
        description: "Total revenue generated by the merchant"
        tests:
          - not_null
      - name: performance_tier
        description: "Performance tier classification based on revenue"
        tests:
          - accepted_values:
              arguments:
                values: ['Top Performer', 'Good Performer', 'Average Performer', 'Underperformer']

  - name: gold_daily_metrics
    description: "Gold layer: Daily financial metrics and KPIs for business reporting"
    columns:
      - name: transaction_date
        description: "Date of transactions"
        tests:
          - unique
          - not_null
      - name: total_transactions
        description: "Total number of transactions on this date"
        tests:
          - not_null
      - name: daily_revenue
        description: "Total revenue generated on this date"
        tests:
          - not_null
      - name: success_rate_percent
        description: "Daily success rate percentage"
        tests:
          - not_null
      - name: day_name
        description: "Name of the day of the week"
        tests:
          - accepted_values:
              arguments:
                values: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']