connection_databricks:
  target: dev_local
  outputs:
    # dev local profile used for dbt development on local mashie with token access
    dev_local:
      type: databricks
      catalog: dbt_blueprint
      schema: default
      host: dbc-a505ff10-0af5.cloud.databricks.com
      http_path: /sql/1.0/warehouses/4fa4ca06332da87f
      token: "{{ env_var('BLUEPRINT_DATABRICKS_TOKEN') }}"
      threads: 1

    dev_cloud:
      type: databricks
      auth_type: oauth
      catalog: dbt_blueprint_prod
      schema: default
      host: dbc-a505ff10-0af5.cloud.databricks.com
      http_path: /sql/1.0/warehouses/4fa4ca06332da87f
      token: "{{ env_var('BLUEPRINT_DATABRICKS_TOKEN') }}"
      threads: 1